include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    always_declare_return_types: true
    directives_ordering: true
    prefer_final_locals: true
    sort_constructors_first: true
