// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    journalMetadata,
    logs,
    collections,
    entries,
    entryPlacements,
    entryPlacementsLogOrdinal,
    entryPlacementsCollectionOrdinal,
    migrations,
    collectionReferences,
    signifiers,
    entrySignifiers,
    indexItems,
    indexItemsLogTarget,
    indexItemsCollectionTarget,
    trackers,
    trackersPeriod,
    trackerMarks,
    trackerMarksMethodDate,
  ];
  late final Shape0 journalMetadata = Shape0(
    source: i0.VersionedTable(
      entityName: 'journal_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 logs = Shape1(
    source: i0.VersionedTable(
      entityName: 'logs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(kind, period_start)'],
      columns: [_column_0, _column_4, _column_5, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 collections = Shape2(
    source: i0.VersionedTable(
      entityName: 'collections',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_6, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 entries = Shape3(
    source: i0.VersionedTable(
      entityName: 'entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((entry_type = \'task\' AND task_state IS NOT NULL)OR(entry_type IN (\'event\', \'note\') AND task_state IS NULL))',
      ],
      columns: [
        _column_0,
        _column_7,
        _column_8,
        _column_9,
        _column_2,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 entryPlacements = Shape4(
    source: i0.VersionedTable(
      entityName: 'entry_placements',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((log_id IS NOT NULL AND collection_id IS NULL)OR(log_id IS NULL AND collection_id IS NOT NULL))',
        'CHECK(collection_id IS NULL OR monthly_section IS NULL)',
        'CHECK((monthly_section = \'calendar\' AND monthly_calendar_date IS NOT NULL)OR(monthly_section IS NULL AND monthly_calendar_date IS NULL)OR(monthly_section = \'tasks\' AND monthly_calendar_date IS NULL))',
      ],
      columns: [
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index entryPlacementsLogOrdinal = i1.Index(
    'entry_placements_log_ordinal',
    'CREATE UNIQUE INDEX entry_placements_log_ordinal ON entry_placements (log_id, ordinal) WHERE log_id IS NOT NULL',
  );
  final i1.Index entryPlacementsCollectionOrdinal = i1.Index(
    'entry_placements_collection_ordinal',
    'CREATE UNIQUE INDEX entry_placements_collection_ordinal ON entry_placements (collection_id, ordinal) WHERE collection_id IS NOT NULL',
  );
  late final Shape5 migrations = Shape5(
    source: i0.VersionedTable(
      entityName: 'migrations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['CHECK(source_entry_id <> destination_entry_id)'],
      columns: [_column_0, _column_16, _column_17, _column_18, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 collectionReferences = Shape6(
    source: i0.VersionedTable(
      entityName: 'collection_references',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(collection_id, entry_id)',
        'UNIQUE(collection_id, ordinal)',
      ],
      columns: [_column_19, _column_20, _column_13, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 signifiers = Shape7(
    source: i0.VersionedTable(
      entityName: 'signifiers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((kind = \'builtin\' AND builtin_code IS NOT NULL AND custom_label IS NULL AND custom_symbol IS NULL)OR(kind = \'custom\' AND builtin_code IS NULL AND custom_label IS NOT NULL AND length(trim(custom_label)) > 0))',
      ],
      columns: [
        _column_0,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 entrySignifiers = Shape8(
    source: i0.VersionedTable(
      entityName: 'entry_signifiers',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(entry_id, signifier_id)'],
      columns: [_column_20, _column_25],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 indexItems = Shape9(
    source: i0.VersionedTable(
      entityName: 'index_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((log_id IS NOT NULL AND collection_id IS NULL)OR(log_id IS NULL AND collection_id IS NOT NULL))',
      ],
      columns: [_column_0, _column_26, _column_11, _column_12, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index indexItemsLogTarget = i1.Index(
    'index_items_log_target',
    'CREATE UNIQUE INDEX index_items_log_target ON index_items (log_id) WHERE log_id IS NOT NULL',
  );
  final i1.Index indexItemsCollectionTarget = i1.Index(
    'index_items_collection_target',
    'CREATE UNIQUE INDEX index_items_collection_target ON index_items (collection_id) WHERE collection_id IS NOT NULL',
  );
  late final Shape10 trackers = Shape10(
    source: i0.VersionedTable(
      entityName: 'trackers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(planned_end_date >= start_date)',
        'CHECK(ended_date IS NULL OR(ended_date >= start_date AND ended_date <= planned_end_date))',
      ],
      columns: [
        _column_0,
        _column_6,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_2,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index trackersPeriod = i1.Index(
    'trackers_period',
    'CREATE INDEX trackers_period ON trackers (start_date, planned_end_date, ended_date)',
  );
  late final Shape11 trackerMarks = Shape11(
    source: i0.VersionedTable(
      entityName: 'tracker_marks',
      withoutRowId: true,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(tracker_id, method_date)'],
      columns: [_column_31, _column_32, _column_33, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index trackerMarksMethodDate = i1.Index(
    'tracker_marks_method_date',
    'CREATE INDEX tracker_marks_method_date ON tracker_marks (method_date)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get singleton =>
      columnsByName['singleton']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<int> _column_1(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'singleton',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 UNIQUE CHECK (singleton = 1)',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (created_at >= 0)',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (updated_at >= created_at)',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get periodStart =>
      columnsByName['period_start']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (kind IN (\'daily\', \'monthly\', \'future\'))',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'period_start',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(period_start) = 10)',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(trim(title)) > 0)',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entryType =>
      columnsByName['entry_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get taskState =>
      columnsByName['task_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get content =>
      columnsByName['content']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entry_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (entry_type IN (\'task\', \'event\', \'note\'))',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'task_state',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (task_state IN (\'open\', \'completed\', \'migrated\', \'scheduled\', \'discarded\'))',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(trim(content)) > 0)',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get entryId =>
      columnsByName['entry_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get logId =>
      columnsByName['log_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get collectionId =>
      columnsByName['collection_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ordinal =>
      columnsByName['ordinal']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get monthlySection =>
      columnsByName['monthly_section']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get monthlyCalendarDate =>
      columnsByName['monthly_calendar_date']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entry_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL PRIMARY KEY REFERENCES entries(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'log_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'REFERENCES logs(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'collection_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'REFERENCES collections(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ordinal',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (ordinal >= 0)',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'monthly_section',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'CHECK (monthly_section IN (\'calendar\', \'tasks\'))',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'monthly_calendar_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'CHECK (monthly_calendar_date IS NULL OR length(monthly_calendar_date) = 10)',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceEntryId =>
      columnsByName['source_entry_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get destinationEntryId =>
      columnsByName['destination_entry_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_entry_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL UNIQUE REFERENCES entries(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'destination_entry_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL UNIQUE REFERENCES entries(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL CHECK (kind IN (\'migrated\', \'scheduled\'))',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get collectionId =>
      columnsByName['collection_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get entryId =>
      columnsByName['entry_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ordinal =>
      columnsByName['ordinal']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'collection_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES collections(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'entry_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES entries(id)ON DELETE CASCADE',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get builtinCode =>
      columnsByName['builtin_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customLabel =>
      columnsByName['custom_label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customSymbol =>
      columnsByName['custom_symbol']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (kind IN (\'builtin\', \'custom\'))',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'builtin_code',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'UNIQUE',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'custom_label',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'custom_symbol',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get entryId =>
      columnsByName['entry_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get signifierId =>
      columnsByName['signifier_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'signifier_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES signifiers(id)ON DELETE CASCADE',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ordinal =>
      columnsByName['ordinal']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get logId =>
      columnsByName['log_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get collectionId =>
      columnsByName['collection_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ordinal',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL UNIQUE CHECK (ordinal >= 0)',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startDate =>
      columnsByName['start_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get plannedEndDate =>
      columnsByName['planned_end_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get endedDate =>
      columnsByName['ended_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get colorSlot =>
      columnsByName['color_slot']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'start_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(start_date) = 10)',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'planned_end_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(planned_end_date) = 10)',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ended_date',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'CHECK (ended_date IS NULL OR length(ended_date) = 10)',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'color_slot',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (color_slot BETWEEN 0 AND 4)',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get trackerId =>
      columnsByName['tracker_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get methodDate =>
      columnsByName['method_date']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get value =>
      columnsByName['value']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'tracker_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES trackers(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'method_date',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (length(method_date) = 10)',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (value IN (-1, 1))',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2),
);
